#!/bin/bash

typing_speed=13

choice=0
where_are_you=1
what_is_here=2
create_place=3
travel=4
destroy=5
leave=6

function the_offer {
  echo "   --- Hello "$USER"! ---

  This script is extremely powerfull,
  and you are free to choose one of
  the options below:

  -- 1 to find out where are you
  -- 2 to see what is here
  -- 3 to create a new place
  -- 4 to travel to a place
  -- 5 to destroy the place
  -- 6 to leave" | pv -qL $typing_speed
  echo -n "
  So, what would it be? " | pv -qL $typing_speed
  read choice
  echo
}

function where_are_you_func {
  echo "  You want to know where are you?" | pv -qL $typing_speed
  echo -n "  You are in " | pv -qL $typing_speed
  location="$PWD"
  echo $location | pv -qL $typing_speed
  echo
}

function what_is_here_func {
  echo "  You want to know what is here? There is:" | pv -qL $typing_speed
  contents=`ls`
  echo "  $contents" | pv -qL $typing_speed
  echo
}

while [ $choice != $leave ]
do
  the_offer
  case $choice in
    $where_are_you)
      where_are_you_func
      ;;
    $what_is_here)
      what_is_here_func
      ;;
    *)
      echo "heh"
      ;;
  esac
done
