.TH CHGRP 1 "21 марта 2019" "GNU coreutils 8.30"

.SH НАЗВАНИЕ
\m[red]chgrp\m[] \- изменить группу пользователей, владеющих файлом

.SH СИНТАКСИС
\fBchgrp\fP \M[green]\m[black][OPTION]...\m[]\M[] GROUP FILE...
\fBchgrp\fP [OPTION]... --reference=RFILE FILE...

.SH ОПИСАНИЕ
Изменить группу владения указанными файлами. С ключом \-\-reference
изменить группу владения указанными файлами согласно группе RFILE

.SH ПАРАМЕТРЫ

.SS ИНФОРМАЦИОННЫЕ СООБЩЕНИЯ

.TP
.B -v, --verbose
- выводить диагностическое сообщение для каждого обработанного файла

.TP
.B -c, --changes
- выводить диагностические сообщение только в случае успешного изменения

.TP
.B -f, --silent, --quiet
- подавлять почти все сообщения об ошибках

.SS РАЗИМЕНОВЫВАНИЕ

.TP
.B --dereference
- разименовывать символические ссылки (по умолчанию)

.TP
.B -h, --no-dereference
- не разименовывать символические ссылки (для систем, способных выставлять
группы непосредственно символическим ссылкам)

.SS ПОВЕДЕНИЕ ОТНОСИТЕЛЬНО КОРНЕВОГО КАТАЛОГА

.TP
.B --no-preserve-root
- не обрабатывать '/' (по умолчанию)

.TP
.B --preserve root
- не выполнять команду рекурсивно на '/'

.SS АЛЬТЕРНАТИВНОЕ ЗАДАНИЕ ГРУППЫ

.TP
.B --reference=\fIRFILE\fP
- установить ту же группу, что и у RFILE

.SS РЕКУРСИВНОЕ ПРИМЕНЕНИЕ

.TP
.B -R, --recursive
- рекурсивно применить изменения ко всем файлам и подкаталогам каталога

.SS ПОВЕДЕНИЕ ОТНОСИТЕЛЬНО СИМВОЛИЧЕСКИХ ССЫЛОК ПРИ РЕКУРСИВНОМ ПРИМЕНЕНИИ

.TP
.B -H
- разименовать, если аргумент является символической ссылкой на директорию

.TP
.B -L
- разименовывать все символические ссылки

.TP
.B -P
- никогда не разименовывать символические ссылки (по умолчанию)

.SS ВСПОМОГАТЕЛЬНЫЕ

.TP
.B --help
- показать помощь и завершить выполнение

.TP
.B --version
- показать информацию о текущей версии утилиты и завершить выполнение

.SH ПРИМЕРЫ ИСПОЛЬЗОВАНИЯ

.TP
chgrp workers /workdir
.TP
передать /workdir во владение группе workers

.SH АВТОР

.TP
Разработано David MacKenzie и Jim Meyering.

.SH СООБЩИТЬ О ПРОБЛЕМЕ

.TP
Онлайн-помощь GNU coreutils: <https://www.gnu.org/software/coreutils/>
